### PR TITLE
Added support for route filters to the application and dispatcher classes

### PR DESCRIPTION
**Pull request by elazar**
Added support for route filters to the application and dispatcher classes, updated the README and unit tests accordingly

### CODE REVIEW

**Comment by whatthejeff** [comment]
What do you think about using the return value from the callback instead of passing by reference?

**Comment by elazar** [comment]
I considered that, but all the code invoking the callbacks would be doing is reassigning the return value back to the same variable. I don't know if the Zend Engine is smart enough to realize this and reuse memory already allocated for that variable value rather than allocating additional memory.

**Comment by whatthejeff** [comment]
I don't believe any additional memory is allocated in these types of situations.  I will run some tests against your code with xdebug tonight and post my findings.

**Comment by whatthejeff** [comment]
Real memory usage seems to be the same using both methods.  Xdebug actually reports slightly higher memory usage for the pass-by-reference solution, though I'm not sure why.

**Comment by elazar** [comment]
In that case, I don't have a problem moving the code to return its result rather than modify a passed-by-reference variable. Suppose I should have done that Xdebug analysis myself. Thanks for being thorough. :) Would you like me to commit that change, or do you want to handle it? I'm fine with either.

**Comment by whatthejeff** [comment]
You can do it.  I'll have some time tonight to pull in the changes.  Thanks again!

**Comment by whatthejeff** [comment]
I'll merge this tonight.  Thanks again @elazar :)

**Pull request merged**
